import { helperCharacters } from './helper-characters';
import { lowercaseLetters } from './lowercase-characters';
import { numbers } from './numeric-characters';
import { uppercaseLetters } from './uppercase-characters';

export const PASSWORD_CHARACTERS = [
  {
    id: 1,
    character: 'Z',
    comp: uppercaseLetters.A,
    type: 'uppercase',
  },
  {
    id: 2,
    character: 'Y',
    comp: uppercaseLetters.B,
    type: 'uppercase',
  },
  {
    id: 3,
    character: 'X',
    comp: uppercaseLetters.C,
    type: 'uppercase',
  },
  {
    id: 4,
    character: 'W',
    comp: uppercaseLetters.D,
    type: 'uppercase',
  },
  {
    id: 5,
    character: 'V',
    comp: uppercaseLetters.E,
    type: 'uppercase',
  },
  {
    id: 6,
    character: 'U',
    comp: uppercaseLetters.F,
    type: 'uppercase',
  },
  {
    id: 7,
    character: 'T',
    comp: uppercaseLetters.G,
    type: 'uppercase',
  },
  {
    id: 8,
    character: 'S',
    comp: uppercaseLetters.H,
    type: 'uppercase',
  },
  {
    id: 9,
    character: 'R',
    comp: uppercaseLetters.I,
    type: 'uppercase',
  },
  {
    id: 10,
    character: 'Q',
    comp: uppercaseLetters.J,
    type: 'uppercase',
  },
  {
    id: 11,
    character: 'P',
    comp: uppercaseLetters.K,
    type: 'uppercase',
  },
  {
    id: 12,
    character: 'O',
    comp: uppercaseLetters.L,
    type: 'uppercase',
  },
  {
    id: 13,
    character: 'N',
    comp: uppercaseLetters.M,
    type: 'uppercase',
  },
  {
    id: 14,
    character: 'M',
    comp: uppercaseLetters.N,
    type: 'uppercase',
  },
  {
    id: 15,
    character: 'L',
    comp: uppercaseLetters.O,
    type: 'uppercase',
  },
  {
    id: 16,
    character: 'K',
    comp: uppercaseLetters.P,
    type: 'uppercase',
  },
  {
    id: 17,
    character: 'J',
    comp: uppercaseLetters.Q,
    type: 'uppercase',
  },
  {
    id: 18,
    character: 'I',
    comp: uppercaseLetters.R,
    type: 'uppercase',
  },
  {
    id: 19,
    character: 'H',
    comp: uppercaseLetters.S,
    type: 'uppercase',
  },
  {
    id: 20,
    character: 'G',
    comp: uppercaseLetters.T,
    type: 'uppercase',
  },
  {
    id: 21,
    character: 'F',
    comp: uppercaseLetters.U,
    type: 'uppercase',
  },
  {
    id: 22,
    character: 'E',
    comp: uppercaseLetters.V,
    type: 'uppercase',
  },
  {
    id: 23,
    character: 'D',
    comp: uppercaseLetters.W,
    type: 'uppercase',
  },
  {
    id: 24,
    character: 'C',
    comp: uppercaseLetters.X,
    type: 'uppercase',
  },
  {
    id: 25,
    character: 'B',
    comp: uppercaseLetters.Y,
    type: 'uppercase',
  },
  {
    id: 26,
    character: 'A',
    comp: uppercaseLetters.Z,
    type: 'uppercase',
  },
  {
    id: 27,
    character: 'z',
    comp: lowercaseLetters.a,
    type: 'lowercase',
  },
  {
    id: 28,
    character: 'y',
    comp: lowercaseLetters.b,
    type: 'lowercase',
  },
  {
    id: 29,
    character: 'x',
    comp: lowercaseLetters.c,
    type: 'lowercase',
  },
  {
    id: 30,
    character: 'w',
    comp: lowercaseLetters.d,
    type: 'lowercase',
  },
  {
    id: 31,
    character: 'v',
    comp: lowercaseLetters.e,
    type: 'lowercase',
  },
  {
    id: 32,
    character: 'u',
    comp: lowercaseLetters.f,
    type: 'lowercase',
  },
  {
    id: 33,
    character: 't',
    comp: lowercaseLetters.g,
    type: 'lowercase',
  },
  {
    id: 34,
    character: 's',
    comp: lowercaseLetters.h,
    type: 'lowercase',
  },
  {
    id: 35,
    character: 'r',
    comp: lowercaseLetters.i,
    type: 'lowercase',
  },
  {
    id: 36,
    character: 'q',
    comp: lowercaseLetters.j,
    type: 'lowercase',
  },
  {
    id: 37,
    character: 'p',
    comp: lowercaseLetters.k,
    type: 'lowercase',
  },
  {
    id: 38,
    character: 'o',
    comp: lowercaseLetters.l,
    type: 'lowercase',
  },
  {
    id: 39,
    character: 'n',
    comp: lowercaseLetters.m,
    type: 'lowercase',
  },
  {
    id: 40,
    character: 'm',
    comp: lowercaseLetters.n,
    type: 'lowercase',
  },
  {
    id: 41,
    character: 'l',
    comp: lowercaseLetters.o,
    type: 'lowercase',
  },
  {
    id: 42,
    character: 'k',
    comp: lowercaseLetters.p,
    type: 'lowercase',
  },
  {
    id: 43,
    character: 'j',
    comp: lowercaseLetters.q,
    type: 'lowercase',
  },
  {
    id: 44,
    character: 'i',
    comp: lowercaseLetters.r,
    type: 'lowercase',
  },
  {
    id: 45,
    character: 'h',
    comp: lowercaseLetters.s,
    type: 'lowercase',
  },
  {
    id: 46,
    character: 'g',
    comp: lowercaseLetters.t,
    type: 'lowercase',
  },
  {
    id: 47,
    character: 'f',
    comp: lowercaseLetters.u,
    type: 'lowercase',
  },
  {
    id: 48,
    character: 'e',
    comp: lowercaseLetters.v,
    type: 'lowercase',
  },
  {
    id: 49,
    character: 'd',
    comp: lowercaseLetters.w,
    type: 'lowercase',
  },
  {
    id: 50,
    character: 'c',
    comp: lowercaseLetters.x,
    type: 'lowercase',
  },
  {
    id: 51,
    character: 'b',
    comp: lowercaseLetters.y,
    type: 'lowercase',
  },
  {
    id: 52,
    character: 'a',
    comp: lowercaseLetters.z,
    type: 'lowercase',
  },
  {
    id: 62,
    character: '9',
    comp: numbers.zero,
  },
  {
    id: 53,
    character: '8',
    comp: numbers.one,
  },
  {
    id: 54,
    character: '7',
    comp: numbers.two,
  },
  {
    id: 55,
    character: '6',
    comp: numbers.three,
  },
  {
    id: 56,
    character: '5',
    comp: numbers.four,
  },
  {
    id: 57,
    character: '4',
    comp: numbers.five,
  },
  {
    id: 58,
    character: '3',
    comp: numbers.six,
  },
  {
    id: 59,
    character: '2',
    comp: numbers.seven,
  },
  {
    id: 60,
    character: '1',
    comp: numbers.eight,
  },
  {
    id: 61,
    character: '0',
    comp: numbers.nine,
  },
  {
    id: 201,
    character: 'backspace',
    comp: helperCharacters.backspace,
  },
  {
    id: 202,
    character: 'capslk',
    comp: helperCharacters.capslk,
  },
  {
    id: 203,
    character: 'signin',
    comp: null,
  },
];
